"use strict";
exports.__esModule = true;
var data_1 = require("./data/data");
var __ql_1 = require("./test/__ql");
var res = __ql_1.__QLfilms(data_1["default"].films);
var res2 = __ql_1.__QLpersons(data_1["default"].persons);
var res3 = __ql_1.__QL(data_1["default"].persons);
console.log(res);
console.log("-------------");
console.log(res3);
exports["default"] = null;
