fragment PersonFragment on Person {
    id
    name
    title
    countries
    imgs
    type
    briefAbout
    about {
        mostPopularFilm {
            h3
            h6top
            h6bot
            id
            img
        }
        paragraphs
    }
    filmography {
        h3
        h6top
        h6bot
        id
        img
    }
    yearsPopular
}

fragment FilmFragment on Film {
    id
    title
    coverIMG
    producedBy
    genres
    countries
    year
    producer {
        h3
        h6top
        h6bot
        id
        imgs
    }
    collage
    briefAbout
    about {
        img
        paragraphs
    }
    acters {
        h3
        h6top
        h6bot
        id
        imgs
    }
}